import './globals.scss'
import Navbar from './components/ui/navigation/Navbar'
import Strips from './components/ui/strips/Strips'
import Footer from './components/ui/navigation/Footer'
import Homepage_Loader_Wrapper from './components/ui/loaders/Homepage_Loader_Wrapper '
import Animation_Wrapper from './components/ui/transitions/Animation_Wrapper'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning={true}>
                <Homepage_Loader_Wrapper>
                    <Animation_Wrapper>
                        <Navbar />
                        <Strips />
                        {children}
                        <Footer />
                    </Animation_Wrapper>
                </Homepage_Loader_Wrapper>
            </body>
        </html>
    )
}
