/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/room_0/room_0.glb -k -K -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/room_0/room_0.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.entrance_path} position={[0, 0, -1.313]} scale={[0.705, 1, 5.219]} />
        <mesh name="ground" geometry={nodes.ground.geometry} material={materials.entrance_ground} position={[0, 0, -20]} scale={[15, 20, 25]} />
        <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials.entrance_path} position={[0, 0.095, -1.313]} scale={[0.538, 1, 5.219]} />
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials.entrance_path} position={[0, 0.095, -1.313]} scale={[0.654, 1, 5.219]} />
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials.entrance_circle} position={[0, 2.008, 0]} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room_0/room_0.glb')
